name: Teste CRUD HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Verificar se index.html existe
        run: |
          if [ -f "index.html" ]; then
            echo "✅ index.html encontrado!"
          else
            echo "❌ index.html NÃO encontrado!"
            exit 1
          fi

      - name: Verificar se index.html contém código JavaScript
        run: |
          if grep -q "<script>" index.html; then
            echo "✅ Código JavaScript detectado em index.html"
          else
            echo "⚠️ Nenhum código JavaScript detectado em index.html"
          fi
